### ISSUE TITLE
Invalid Value

### ISSUE THREAD

**Issue by moi6767** [fmartinou/teleinfo2mqtt#30]
Bonjour,

J'avais la version 6.1.0 avec un linky en mode historique sans aucun soucis.

J'ai installé la dernière version en date, je suis toujours en mode historique et depuis j'ai plusieurs warning.

21:25:07.403  WARN teleinfo2mqtt: Invalid value received for label IINST1 [003]
21:25:07.539  WARN teleinfo2mqtt: Invalid value received for label IINST2 [001]
21:25:07.675  WARN teleinfo2mqtt: Invalid value received for label IINST3 [005]
21:25:07.801  WARN teleinfo2mqtt: Invalid value received for label IMAX1 [060]
21:25:07.928  WARN teleinfo2mqtt: Invalid value received for label IMAX2 [060]
21:25:08.056  WARN teleinfo2mqtt: Invalid value received for label IMAX3 [060]
21:25:08.201  WARN teleinfo2mqtt: Invalid value received for label PMAX [04575]
21:25:08.764  WARN teleinfo2mqtt: Invalid value received for label PPOT [00]

J'ai restauré la version 6.1.0 et les soucis on disparu. J'utilise l'installation via l'addon pour home assistant.

**Comment by fmartinou** [comment]
Bonjour,

Depuis la version 8, il y a effectivement des contrôles sur les trames qu'il n'y avait pas auparavant.
Et dans le lot, il y a certainement des erreurs...
A titre perso, je suis en HISTORIQUE aussi mais je ne vois pas passer toutes les étiquettes car je suis en abonnement BASE.
C'est pour cela que je n'ai pas vu la régression ; je vais corriger.

**Comment by fmartinou** [comment]
Je viens de comprendre ; il manque la gestion des étiquettes pour le triphasé 🤔

**Comment by fmartinou** [comment]
C'est corrigé dans la version `8.0.2`

**Comment by moi6767** [comment]
Je viens de tester je confirme c'est parfaitement fonctionnel 👍 . 
Merci pour la correction rapide du soucis et pour ce superbe projet.
