### ISSUE TITLE
Help debug plus de données 

### ISSUE THREAD

**Issue by pbox** [fmartinou/teleinfo2mqtt#40]
Hello,

J'ai migré depuis domoticz vers ton addon teleinfo2mqtt sur HA. J'ai eu des données sans probleme pendant les 12 premieres heures et depuis plus rien.

Le log n'est pas tres explicite, ainsi serait il possible de partager des astuces pour tenter de resoudre le probleme ?

21:40:28.651  INFO teleinfo2mqtt: Connecting to port [/dev/ttyUSB1] with history TIC mode
21:40:28.666  INFO teleinfo2mqtt: Connected to port [/dev/ttyUSB1]
21:40:28.673  INFO teleinfo2mqtt: Connecting to MQTT broker [mqtt://192.168.0.150:1883]
21:40:28.951  INFO teleinfo2mqtt: Connected to MQTT broker [mqtt://192.168.0.150:1883]

![image](https://user-images.githubusercontent.com/5003483/199920154-886be711-092a-4cfe-b6bf-73c2d1a64bbc.png)

Merci d'avance !

**Comment by fmartinou** [comment]
Hello,

Tu devrais pouvoir changer le niveau de log de info vers debug.
Ca te permettra d'avoir (beaucoup) plus d'infos.

**Comment by fmartinou** [comment]
Je cloture l'issue pour cause d'inactivité ; n'hésitez pas à la rouvrir s'il y a besoin.
