### ISSUE TITLE
erreur lors du lancement du container avec un Raspberry Pi Model B Rev 2

### ISSUE THREAD

**Issue by duberic31** [fmartinou/teleinfo2mqtt#43]
Bonjour
Voilà ce que j'ai comme erreur aprés avoir lancé avec docker compose up

pi@raspberrypi:/usr/local/bin $ docker compose up
[+] Running 2/2
 ⠿ Network bin_default      Created                                             2.2s
 ⠿ Container teleinfo2mqtt  Created                                             2.4s
**Attaching to teleinfo2mqtt
**_Error response from daemon: failed to create shim task: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v2.task/moby/dba89de7bbdbe6dff64704180fead7123d26e327b54ba16ea81a48d903359173/log.json: no such file or directory): runc did not terminate successfully: exit status 132: unknown**_**
Une idée du probléme ?
Merci

**Comment by duberic31** [comment]
Bon, je me réponds, j'avais un pb avec ma config de mon raspbian.
Je viens de charger une nouvelle image et de tout reconfigurer
Ca devrait marcher maintenant

**Comment by fmartinou** [comment]
OK 😁 

N'hésite pas à rouvrir l'issue si jamais l'erreur n'est pas résolue 😃
