### ISSUE TITLE
Valeurs linky en Wh avec des mesures aberrantes de temps en temps (TEMPO)

### ISSUE THREAD

**Issue by eetasse** [fmartinou/teleinfo2mqtt#46]
Bonjour,

Déjà merci et bravo pour ce plug-in ! Je débute avec HA mais j'avais dans le passé réalisé moi-même un montage électronique pour brancher mon compteur (historique) sur mon raspberry 1 avec Domoticz.

EDF vient de passer mon Linky en TIC Standard (sur ma demande) mais je rencontre maintenant des soucis (en Standard tout marchait bien). J'ai paramétré HA Energy sur la base des explications trouvé sur le net (utiliser les mesures _easf0X) pour récupérer les HC/HP des jours B, W et R car je suis en abonnement TEMPO.

Ce que j'observe :
* les mesures sont remontées en Wh et HA Energy les souhaite en kWh (=> j'ai compris que je peux faire des template sensors pour convertir en kWh
* des Warning dans le log de Teleinfo2Mqtt (ci-dessous)
* des consommations aberrantes dans HA Energy : consommation de plusieurs tarifs en même temps (voir image)
* des mesures "bizarres" quand le regarde les courbes temporelles : quelques mesures proche du Zéro ou bien sur d'autres valeurs précises : plusieurs valeurs dans la journée (voir image plus bas)

Avant de mettre en place des template sensors, est-ce que j'ai raté quelque chose d'autre ? Est-ce qu'il y a un problème dans la configuration du Linky par EDF ? HA Energy et Teleinfo2Mqtt supportent ils le TEMPO ?

Merci bcp pour votre aide !   

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/1891460/217552917-5346fe6e-f771-4826-87e0-51867c3e91f1.png">

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/1891460/217593054-e9bafa7d-5007-4a7e-9045-f95fec12d492.png">

<img width="2155" alt="image" src="https://user-images.githubusercontent.com/1891460/217594448-383ae9ca-45d2-4221-9f77-705d8cda5d99.png">

17:35:30.703  WARN teleinfo2mqtt: Invalid value received for label PPOINTE [00004005 06004006 22004005 NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE]
17:35:31.634  WARN teleinfo2mqtt: Error on parsing the value [00] and the timestamp [ 230208060000] for label [DPM2]: [Invalid timestamp ( 230208060000]
17:35:31.650  WARN teleinfo2mqtt: Error on parsing the value [00] and the timestamp [ 230209060000] for label [FPM2]: [Invalid timestamp ( 230209060000]
17:35:32.025  WARN teleinfo2mqtt: Invalid value received for label PPOINTE [00004005 06004006 22004005 NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE]
17:35:32.439  WARN teleinfo2mqtt: Invalid value received for label EARD03 [006675554]
17:35:32.967  WARN teleinfo2mqtt: Error on parsing the value [00] and the timestamp [ 230208060000] for label [DPM2]: [Invalid timestamp ( 230208060000]
17:35:32.983  WARN teleinfo2mqtt: Error on parsing the value [00] and the timestamp [ 230209060000] for label [FPM2]: [Invalid timestamp ( 230209060000]
17:35:33.367  WARN teleinfo2mqtt: Invalid value received for label PPOINTE [00004005 06004006 22004005 NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE]
17:35:34.294  WARN teleinfo2mqtt: Error on parsing the value [00] and the timestamp [ 230208060000] for label [DPM2]: [Invalid timestamp ( 230208060000]

**Comment by spamoi33** [comment]
Hello, regarde dans Settings / Devices & Services / Entities / ton entité "HP Bleu" par exemple puis onglet Settings, chez moi en "Unit of Measurement" j'ai "Wh" et ça fonctionne bien comme ça.

**Comment by eetasse** [comment]
J'ai bien Wh comme unité de mesure. J'ai créer des sensor templates (configuration.yaml) pour simplement diviser par 1000 les valeurs envoyées par téléfinfo template et tout fonctionne bien depuis... 
Exemple : 
  - sensor:
      - name: "EDFLINKY HCJB KWH"
        unit_of_measurement: kWh
        state: "{{ (states('sensor.teleinfo_xxxxxxxxx_easf01') | float / 1000) | round(2) }}"
        device_class: energy
        state_class: total
On peut clore l'issue je pense de mon côté... bizarre de devoir ajouter cette conversion...

**Comment by eetasse** [comment]
Je n'utilise plus le montage fait maison, mais ce boîtier acheté chez cge electronics 
https://www.gce-electronics.com/fr/carte-electronique-oem-relais-usb/655-module-teleinfo-usb.html
Le boîtier est connecté sur un raspberry pi 4 avec HA OS dessus.

**Comment by eetasse** [comment]
Diviser les mesures par 1000 pour obtenir des kWh améliore, mais il y a toujours des valeurs aberrantes capable de faire remonter des sur-conso et sous-conso qui se compensent (voir captures d'écran). Je me demande si c'est possible qu'il y ait des interférences / parasites sur le cable entre le compteur et le boîtier teleinfo (10m de cable non blindé)... qui change des caractères / valeurs sur le signal ???

<img width="490" alt="image" src="https://user-images.githubusercontent.com/1891460/218307570-fa1a00b5-a27f-4960-ac54-ecf8cfedec04.png">

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/1891460/218307606-6c879e5e-5fba-4850-a325-2bed450cb56a.png">

**Comment by spamoi33** [comment]
On dirait qu’il y a des micro-coupures effectivement. 10m sans masse c’est probablement pas top.

**Comment by eetasse** [comment]
J'ai changé le cable avec du cable réseau (paires torsadées, blindé) mais j'ai toujours des valeurs aberrantes... je crois que je vais appeler cge-electronique (support à 2 eur / appel) :-(

**Comment by eetasse** [comment]
Je n'ai pas de tel switch sur le boîtier gce-electronics. J'ai fait de nombreux tests pour essayer de comprendre d'où vient le problème. 
* ce n'est pas la longueur de cable car le problème est reproduit en me branchant directement derrière le linky
* j'ai testé le boîtier gce-electronics sur un vieux raspberry pi en comparant les trames envoyées par mon "vieux" montage électronique, je ne trouve rien de probant (en écoutant le port)
* j'aimerai injecté les trames du linky avec mon vieux montage mais je ne sais pas (je n'arrive pas) à envoyer les trames vers un /dev/ttyAMA0 ou ttyUSB0 sur le raspberry où tourne home assistant OS... 
* ce matin, j'ai testé un autre cable USB (du boitier cge vers le raspberry) et chose que je ne m'explique pas : pas de valeurs aberrantes, aucun WARN dans teleinfo2mqtt.... 6 heures après je remplace avec l'ancien câble et alors j'ai des warning dans le log teleinfo2mqtt => je pense avoir trouvé la raison de mon problème... je remets alors le nouveau câble USB... et alors le log teleinfo2mqtt continue à envoyer des warnings chaque seconde... 
bref je deviens un peu fou... 
En regardant de plus près les warning de teleinfo2mqtt je trouve des message à propos de valeurs corrompues, mais  certaines valeurs sont correctes... exemple : 

WARN teleinfo2mqtt: Invalid value received for label EARF05 [000692136]

la valeur est bien correcte (ici c'est du tempo HC jour rouge) mais le label devrait être plutôt EASF05 et non EARF05...

**Comment by spamoi33** [comment]
Il va falloir à songer de boitier TIC alors !
J'ai celui-ci : https://www.domotique-store.fr/domotique/modules-domotiques/detecteurs-capteurs-mesure/mesure-consommation-energetique/672-module-teleinfo-usb-cartelectronic-usbticlc-win.html et aucun problème :)

**Comment by eetasse** [comment]
ça m'embête d'acheter un autre boîtier sans comprendre d'ou vient le problème. J'ai tout de même acheté "usb to ttl" à 7 euros pour envoyer les trames de mon montage électronique sur le port USB0 du Raspberry pi 4. Ca fonctionne depuis peu et je vais surveiller qu'il n'y pas de valeurs aberrantes qui remontent dans HA d'ici 24-48h. Ca démontrera alors que c'est bien le boitier qui est en cause.

**Comment by spamoi33** [comment]
Alors, du nouveau ? :)

**Comment by lunarok** [comment]
Hello,
J'ai le meme soucis je pense avec des valeurs qui semblent tronquées (genre parfois il envoit 38 au lieu de 3847638938)
Du coup c'est ca qui pourrit les tableaux energy de HA car quand il prend en compte le passage suivant en "retour à la normale" de valeur pour une consommation, donc chiffre délirant.
J'ai vérifié le cablage, en serial je vois bien par moment des lignes incorrectes. Ne serait-il pas possible de faire comme les autres messages en warning car valeur incorrecte, de dropper les lectures d'index dont la valeur est inférieure à la précédente ?

**Comment by fmartinou** [comment]
Salut,

J'ai appliqué la proposition de @lunarok (drop le message si une valeur d'index est inférieure à la valeur précédente).
Je n'ai pas pu le tester personnellement car je ne rencontre pas le problème en question 🤞 .

**Comment by fmartinou** [comment]
Released as `8.3.1`.
