### ISSUE TITLE
Erreur sur les trames PPOINTE , DPM1 , FPM1 

### ISSUE THREAD

**Issue by zekje** [fmartinou/teleinfo2mqtt#47]
Bonjour,
J utilise un module rail din USB sur ma téléinfo ( linky mode standard et contrat tempo )

depuis quelques jours je m aperçoit que le INST n'est pas mis à jour pendant un long temps ( plus d une heure quand je m en aperçoit ) , alors que j'ai mis un rafraichissement à 15s ....

en regardant dans les logs, je vois ça toutes les secondes ( pourquoi si j ai un refresh a 15s ?  )

`11:59:56.304  WARN teleinfo2mqtt: Error on parsing the value [00] and the timestamp [ 230214060000] for label [FPM1]: [Invalid timestamp ( 230214060000]
11:59:56.672  WARN teleinfo2mqtt: Invalid value received for label PPOINTE [00004003 06004004 22004003 NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE]
11:59:57.376  WARN teleinfo2mqtt: Error on parsing the value [00] and the timestamp [ 230213060000] for label [DPM1]: [Invalid timestamp ( 230213060000]`

en debug pour avoir plus d infos : 

`11:50:12.591 DEBUG teleinfo2mqtt: Raw frame [PPOINTE	00004003 06004004 22004003 NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE	!
]
11:50:12.592 DEBUG teleinfo2mqtt: Split frame [PPOINTE,00004003 06004004 22004003 NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE,!
]
11:50:12.592  WARN teleinfo2mqtt: Invalid value received for label PPOINTE [00004003 06004004 22004003 NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE]

11:56:46.322 DEBUG teleinfo2mqtt: Raw frame [DPM1	 230213060000	00	^
]
11:56:46.322 DEBUG teleinfo2mqtt: Split frame [DPM1, 230213060000,00,^
]
11:56:46.322 DEBUG teleinfo2mqtt: Value for label DPM1 = 00
11:56:46.322  WARN teleinfo2mqtt: Error on parsing the value [00] and the timestamp [ 230213060000] for label [DPM1]: [Invalid timestamp ( 230213060000]
11:56:46.337 DEBUG teleinfo2mqtt: Raw frame [FPM1	 230214060000	00	!
]
11:56:46.338 DEBUG teleinfo2mqtt: Split frame [FPM1, 230214060000,00,!
]
11:56:46.338 DEBUG teleinfo2mqtt: Value for label FPM1 = 00
11:56:46.338  WARN teleinfo2mqtt: Error on parsing the value [00] and the timestamp [ 230214060000] for label [FPM1]: [Invalid timestamp ( 230214060000]`

est ce que c est normal ?
comment le corriger ?

**Comment by zekje** [comment]
peut t on ne pas remonter les infos non interessantes , ex PPOINTE DPM1
FPM1 , ca ferais moins de données a traiter ?

**Comment by fmartinou** [comment]
> peut t on ne pas remonter les infos non interessantes , ex PPOINTE DPM1
FPM1 , ca ferais moins de données a traiter ?

A ce jour, il n'est pas possible d'ignorer une liste d'étiquettes.
Je ne pense pas que ça soit utile à implémenter puisque ce qui fait vraiment la différence, c'est de jouer sur le `EMIT_INTERVAL`.

-----

> en regardant dans les logs, je vois ça toutes les secondes ( pourquoi si j ai un refresh a 15s ? )

Le refresh influe sur le fait d'envoyer ou non la trame via mqtt mais n'influe pas sur la lecture des trames sur le port série, qui elle est faite en continu (1 trame par seconde).

-----

> 11:59:56.304  WARN teleinfo2mqtt: Error on parsing the value [00] and the timestamp [ 230214060000] for label [FPM1]: [Invalid timestamp ( 230214060000] 11:59:56.672  WARN teleinfo2mqtt: Invalid value received for label PPOINTE [00004003 06004004 22004003 NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE] 11:59:57.376  WARN teleinfo2mqtt: Error on parsing the value [00] and the timestamp [ 230213060000] for label [DPM1]: [Invalid timestamp ( 230213060000]

Il y a peut-être une erreur de code sur la gestion du FPM1 => je vais regarder.

**Comment by fmartinou** [comment]
J'ai fait un fix qui peut être testé avec la version `fmartinou/teleinfo2mqtt:fix__47_ppointe`.

@zekje ; peux-tu tester ?
(mon compteur n'est pas en mode STANDARD)

Si ok , alors je ferai une release.
