### ISSUE TITLE
Publish latest version (currently 8.3.3) to docker hub

### ISSUE THREAD

**Issue by reaper** [fmartinou/teleinfo2mqtt#59]
Hi, first thanks for the great job !

I just figured out that the latest available version on docker hub has been pushed 1 year ago (7.0.2): can you please build and push each tag to docker hub? https://hub.docker.com/r/fmartinou/teleinfo-mqtt/tags

Or do I miss something ? please advice.
Thank you!

**Comment by fmartinou** [comment]
Hi!

The image has been renamed last year.
![image](https://github.com/fmartinou/teleinfo2mqtt/assets/16061231/a8f5751c-23c4-4245-b138-5b1304b3d8e3)

The latest image on Docker hub is here:
https://hub.docker.com/r/fmartinou/teleinfo2mqtt

Regards,
