### ISSUE TITLE
Segmentation fault on pi3

### ISSUE THREAD

**Issue by solune** [fmartinou/teleinfo2mqtt#71]
Hello,
I'm running 9.0.1 and I get this error on my pi3B+

`pi@raspberrypi:~/teleinfo2mqtt $ sudo docker-compose up
Starting teleinfo2mqtt ... done
Attaching to teleinfo2mqtt
teleinfo2mqtt    | 16:16:42.169  INFO teleinfo2mqtt:
teleinfo2mqtt    |     Starting teleinfo2mqtt with configuration = {
teleinfo2mqtt    |       emitInterval: 10,
teleinfo2mqtt    |       hassDiscovery: true,
teleinfo2mqtt    |       hassDiscoveryPrefix: 'homeassistant',
teleinfo2mqtt    |       logLevel: 'debug',
teleinfo2mqtt    |       mqttBaseTopic: 'teleinfo',
teleinfo2mqtt    |       mqttUrl: 'mqtt://192.168.1.100:1883',
teleinfo2mqtt    |       mqttUser: 'teleinfo',
teleinfo2mqtt    |       mqttPassword: '<hidden>',
teleinfo2mqtt    |       mqttTlsClientKey: undefined,
teleinfo2mqtt    |       mqttTlsClientCert: undefined,
teleinfo2mqtt    |       mqttTlsCaChain: undefined,
teleinfo2mqtt    |       mqttTlsRejectUnauthorized: true,
teleinfo2mqtt    |       serial: '/dev/ttyUSB0',
teleinfo2mqtt    |       tempoEnabled: true,
teleinfo2mqtt    |       tempoIntervalMinute: '10',
teleinfo2mqtt    |       ticMode: 'standard'
teleinfo2mqtt    |     }
teleinfo2mqtt    | 16:16:42.194  INFO teleinfo2mqtt: Connecting to port [/dev/ttyUSB0] with standard TIC mode
teleinfo2mqtt    | Segmentation fault (core dumped)
teleinfo2mqtt exited with code 0`

Have you any idea to solve it ?
Regards

**Comment by fmartinou** [comment]
It's probably the same issue as #26.

I need to find a definitive solution; I cannot stay forever on a lib deprecated from years 😞

**Comment by fmartinou** [comment]
Hi @solune ,

Could you give a try to this version, please?
```
fmartinou/teleinfo2mqtt:fix__71_arm_segfault
```

**Comment by solune** [comment]
This version works well
Thanks

**Comment by fmartinou** [comment]
That's a very good news 👍 

I'll release an official fixed version.

**Comment by fmartinou** [comment]
Released as ` 9.0.2`
