### ISSUE TITLE
Entité manquante dans HA ?

### ISSUE THREAD

**Issue by fredarro** [fmartinou/teleinfo2mqtt#75]
Je suis en mode Standard.
Est-il normal de ne pas avoir la valeur SINSTS dans HA alors que je la vois bien sur mon broker MQTT ?

**Comment by fredarro** [comment]
Oui tout est bien présent dans la trame mais dans HA plus rien à partir NJOURF
C'est à dire que les entités suivantes n'apparaissent pas dans HA :
NJOURF+1 
NTARF 
PCOUP 
PJOURF+1 
PPOINTE 
PREF 
PRM 
RELAIS 
SINSTI 
SINSTS 
SINSTS1 
SINSTS2 
SINSTS3 
SMAXIN 
SMAXIN-1 
SMAXSN 
SMAXSN-1 
SMAXSN1 
SMAXSN1-1 
SMAXSN2 
SMAXSN2-1 
SMAXSN3 
SMAXSN3-1 
STGE 
UMOY1 
UMOY2 
UMOY3 
URMS1 
URMS2 
URMS3 
VTIC

**Comment by fmartinou** [comment]
Il y a des warnings ou des erreurs dans les logs du module ?

**Comment by fredarro** [comment]
Non, rien Pas d'erreur ou de warning
Toutes les entités arrivent bien sur le Broker MQTT.
On dirait une limitation à 40 entités remontées de MQTT vers HA par ordre alphabétique.

**Comment by fmartinou** [comment]
C'est potentiellement le même problème que https://github.com/fmartinou/teleinfo2mqtt/issues/16#issuecomment-1817828624.

Le  problème avec un `+` dans le nom du topic qui n'est pas valide d'un point de vue `mqtt`.
Ce qui expliquerait pourquoi c'est à partir de `NJOURF+1`, que ça ne remonte plus 🤔 .

Faut que je prenne le temps de renommer tous ces `+`

**Comment by fredarro** [comment]
Super, tu as surement raison et le `+` doit être à l'origine du problème.
Nous attendrons le renommage.

**Comment by spamoi33** [comment]
Hello @fmartinou , tu dis "d'un point de vue mqtt" mais pourtant les valeurs sont OK quand on regarde avec un "explorateur" mqtt. C'est HA qui n'arrive pas à lire les infos du broker du coup ?

**Comment by fmartinou** [comment]
Les données publiées au format JSON dans le topic mqtt `teleinfo/$adsc` ne posent pas de problème car les `+` sont juste des caractères apparaissant dans le nom des clés du document JSON ; c'est parfaitement valide.


Le problème vient probablement plutôt des topics qui servent à publier la configuration des sensors dans HA (pour la découverte automatique des sensors par HA).
Ce sont les topics apparaissant sous ` homeassistant/sensor/teleinfo/$adsc_$label/config`)

Ces topics, que le module cherche à créer, contiennent des `+` dans leurs noms pour les étiquettes `NJOURF+1`...
Exemple  :
```
 homeassistant/sensor/teleinfo/0123456789_njourf+1/config
```

or le `+` a une signification en mqtt (c'est un wildcard) donc je suppose que le problème vient de là.

**Comment by stephanlascar** [comment]
J'avais regardé dans mqttexplorer, en effet les noeuds à partir du NJOURF+1 (inclu) ne sont pas publié dans le discovery

**Comment by ThibautBascoulergue** [comment]
Bonjour,
Est-ce qu'on a une solution pour ce problème, depuis la dernière mise à jours de HA je n'ai plus certaines valeurs comme évoqué au-dessus.
Merci

**Comment by Balakao** [comment]
> Bonjour, Est-ce qu'on a une solution pour ce problème, depuis la dernière mise à jours de HA je n'ai plus certaines valeurs comme évoqué au-dessus.
> 
> ![image](https://private-user-images.githubusercontent.com/42678960/288351040-4a800d1d-68cb-4b64-8031-c7cbeb5ab3d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NzIxOTksIm5iZiI6MTcwMTg3MTg5OSwicGF0aCI6Ii80MjY3ODk2MC8yODgzNTEwNDAtNGE4MDBkMWQtNjhjYi00YjY0LTgwMzEtYzdjYmViNWFiM2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDE0MTEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMTYzYjZhMjc1M2NjNGVkMzE1YzI1NzMzMWY3ZmY0MTdiNDQ4MzQ3NTcxYmY1NjgyMzNmNWQ3ODJhZGQwNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hRIfGi95K1zd9WEDwsfiDaOpaH5QCxaS5GhZqeWPrIg) ![image](https://private-user-images.githubusercontent.com/42678960/288351183-da6d0e6e-fdc7-49a5-a495-cfce5dff43f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NzIxOTksIm5iZiI6MTcwMTg3MTg5OSwicGF0aCI6Ii80MjY3ODk2MC8yODgzNTExODMtZGE2ZDBlNmUtZmRjNy00OWE1LWE0OTUtY2ZjZTVkZmY0M2Y4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDE0MTEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZTQ3NTIzOTVmYTY0NTZlYjNkNTQ5ZmEyNGQ4OTE0N2M4ZDAwZjFhODU1YWI4OWMzOGFkODQ0NTQ1MTdmNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pMfm3VQB0dfhY3ngkevW7XiZz2O1CIVSy9RVRlxU_h4)
> 
> Merci

Salut,

De mon côté, j'ai filtré les entités par sensor.linky, et j'ai fait un par un pour chaque compteur :
- récupération de l'ID du compeur
- suppression du compteur obsolète (ça ne supprime pas l'historique)
- renommage du nouveau compteur avec l'id de l'ancien

Ex : sensor.linky_012345678910_teleinfo_012345678910_bbrhcjw (nom de l'ancien compteur), on récupère le nom sans sensors., on va sur le nouveau compteur sensor.linky_012345678910_bbrhcjw, et on remplace linky_012345678910_bbrhcjw par sensor.linky_012345678910_teleinfo_012345678910_bbrhcjw.

Ça permet de remettre à flot sans avoir à tout reconfigurer et perdre les historiques. Penser à bien faire une sauvegarde avant, modifier, et faire un reboot pour bien s'assurer que ça fonctionne sans surprise (quand on fait un reboot 3 semaines après, on a tendance à ne plus faire le lien entre update et conneries).

**Comment by ThibautBascoulergue** [comment]
Ok , merci

**Comment by fmartinou** [comment]
Fixed as `9.0.3`

**Comment by spamoi33** [comment]
Merci pour la correction @fmartinou  :)
Bon, c'est juste un peu pénible de devoir tout "recabler" derrière, mais au moins ça fonctionne ^^

Par curiosité, pourquoi certains sensors sont dupliqués ? exemple, j'ai 3 SINSTS (sinsts1 => 3)

Bon dimanche !

**Comment by fmartinou** [comment]
Merci pour le feedback.
Les 3 sinsts font partie de la spécification du protocole en mode standard.
Je pense que c'est pour les installations en triphasé.
Cdt

**Comment by spamoi33** [comment]
Ah ok, je ne suis pas en triphasé pourtant. Ca ne gêne pas plus que ça.

**Comment by fmartinou** [comment]
> Ah ok, je ne suis pas en triphasé pourtant. Ca ne gêne pas plus que ça.

Tous les sensors du mode standard sont automatiquement créés quels que soient l'abonnement et les caractéristiques du compteur (monophasé, triphasé...).

Voir [Enedis-NOI-CPT_54E](https://www.enedis.fr/media/2035/download)[](https://www.enedis.fr/media/2035/download) pour avoir la liste exhaustive.

**Comment by spamoi33** [comment]
Effectivement... ça ne m'avait sauté aux yeux 👀

**Comment by spamoi33** [comment]
Hello,

J'ai donc modifier les sources de mon dashboard Energie, du coup forcement j'ai perdu tous les historiques de ma consommation :|

Quelqu'un aurais une idée pour transférer les données ? ❤️

**Comment by spamoi33** [comment]
Personne ? :( je n'ai plus aucune consommation sur le dashboard energy avant le problème de nom de topic MQTT :'(

Comment faites vous ??
